apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: say-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: say
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: say
        image: gcr.io/sanjaesan/say
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: say-service
spec:
  selector:
    app: say
  ports:
    - protocol: TCP
      port: 8080
